# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., ['vugule1', 'majkasgurunu']
patreon: # Replace with a single Patreon username e.g., ['andymarkovic']
open_collective: # Replace with a single Open Collective username e.g., ['andymarkovic']
ko_fi: # Replace with a single Ko-fi username e.g., ['andymarkovic']
liberapay: # Replace with a single Liberapay username e.g., [andymarkovic]
issuehunt: # Replace with a single IssueHunt username e.g., ['andymarkovic']
polar: # Replace with a single Polar username e.g., ['andymarkovic']
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username e.g., ['andymarkovic']
thanks_dev: # Replace with a single thanks.dev ussername e.g., [username]
custom: # Replace with up to 4 custom sponsorship URLs e.g., 'https://www.android.com/sponsor e.g., ['partner']', 'https://www.google.com/partner e.g., ['username']', 'https://www.microsoft.com/partner e.g., ['username]', ' https://osiris.com/partner e.g., ['username']'
